# ---------------------------------------------------------------
# Production profile ? activated with: --spring.profiles.active=prod
# ---------------------------------------------------------------

eureka.client.serviceUrl.defaultZone=${EUREKA_URL}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

management.tracing.export.zipkin.endpoint=${ZIPKIN_URL}
management.tracing.sampling.probability=1.0

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=when-authorized