spring.application.name=user-service
server.port=8081

# Fetch secrets from the Central Vault
spring.config.import=optional:configserver:http://localhost:8888

# Register with the Phonebook
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Database Configuration (Reusing your monolith DB for now)
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/mydatabase?timezone=UTC
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Local fallback ? config-server overrides this if it's up
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.endpoints.web.exposure.include=*