spring.application.name=eureka-server

# Standard port for Eureka
server.port=8761

# Tell Eureka NOT to register itself in its own phonebook
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
